spring:
  datasource:
    url: jdbc:postgresql://stablishment-db:5432/stablishment_db
    driver-class-name: org.postgresql.Driver
    username: stablishment_user
    password: stablishment_pass

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  servicescredential:
    apiUrl: http://auth-service:8080/api-key/get-public-key
    authServiceUrl: http://auth-service:8080/api/auth/
    productServiceUrl: http://product-service:8080/products
    incentive-service-user-points-url: http://incentive-service:8080/v1/user-points
    incentive-service-stablishment-configuration-url: http://incentive-service:8080/v1/stablishment-configurations