server:
  port: 8082
spring:
  web:
    error:
      include-message: always
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
app:
    servicescredential:
        password: servicepass
        apiUrl: http://localhost:8081/api-key/get-public-key
        authServiceUrl: http://localhost:8081/api/auth/
        establishment-service-stablishment-url: http://localhost:8080/stablishments
        incentive-service-incentive-url: http://localhost:8083/v1/incentives