spring:
  datasource:
    url: jdbc:postgresql://product-db:5432/product_db
    driver-class-name: org.postgresql.Driver
    username: product_user
    password: product_pass

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  servicescredential:
    apiUrl: http://auth-service:8080/api-key/get-public-key
    authServiceUrl: http://auth-service:8080/api/auth/
    establishment-service-stablishment-url: http://stablishment-service:8080/stablishments
    incentive-service-incentive-url: http://incentive-service:8080/v1/incentives

